### ISSUE TITLE
Tipje :) Meer info in alt

### ISSUE THREAD

**Issue by xxdaniquee** [MisahSaid/the-startup-responsive-interactieve-website#10]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/7e5000b02217e6c58498d706fa60e69508635c7a/index.html#L12

Ik zou bij alt duidelijker neer zetten dat het een logo van van just voor de toegankelijkheid.
Nu is het voor een gebruiker van een screen reader niet duidelijk wat van Just op deze afbeelding staat.
alt="Just logo"

Hier meer info over alt: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

**Comment by MisahSaid** [comment]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/commit/b0a29194a86a671d4c0fd3afc5f450bbb8bdf5f6
