### ISSUE TITLE
in root

### ISSUE THREAD

**Issue by xxdaniquee** [MisahSaid/the-startup-responsive-interactieve-website#4]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/08c6de6e33584a42a836906747068b9fcd21aab9/stylesheet.css#L57C5-L57C20\

Zou deze kleur ook in de root zetten, dan heb je al je kleuren bij elkaar en kan je overal var gebruiken

**Comment by MisahSaid** [comment]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/d8f8593f105034562525ee87680f55da183dd719/stylesheet.css#L2-L9
