### ISSUE TITLE
Sections zonder headings

### ISSUE THREAD

**Issue by lemuelmgsn** [MisahSaid/the-startup-responsive-interactieve-website#5]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/7e5000b02217e6c58498d706fa60e69508635c7a/index.html#L35-L39

https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/7e5000b02217e6c58498d706fa60e69508635c7a/index.html#L41-L43

https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/7e5000b02217e6c58498d706fa60e69508635c7a/index.html#L48-L53

Je hebt bij deze sections geen headings staan.

Je zou de sections kunnen veranderen in divs waar je geen text bij hebt of je kan van de paragraphs er headings van maken. 

Bron: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

**Comment by MisahSaid** [comment]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/commit/1712a34e9c7429df438f43722f95b59f321121c0
