### ISSUE TITLE
Typefoutje "imput"

### ISSUE THREAD

**Issue by lemuelmgsn** [MisahSaid/the-startup-responsive-interactieve-website#6]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/7e5000b02217e6c58498d706fa60e69508635c7a/index.html#L67

Ik denk dat je hier input bedoelde :)

**Comment by MisahSaid** [comment]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/commit/79a87fde2f9c793fac5adcb134a680197a032ebe
