### ISSUE TITLE
Je bent wat H elementjes vergeten bij je sections

### ISSUE THREAD

**Issue by xxdaniquee** [MisahSaid/the-startup-responsive-interactieve-website#8]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/7e5000b02217e6c58498d706fa60e69508635c7a/index.html#L35

In deze section heb je geen H element gebruikt. Er zijn 2 opties om dit op te lossen:
1. Een H element toevoegen
2. Een div ervan maken.

Hier is meer info :) https://www.w3docs.com/snippets/html/what-is-the-difference-between-section-and-div-elements.html

**Comment by MisahSaid** [comment]
hihi veranderd naar een div omdat het niet nodig was om een section van te maken:
[Section --> Div](https://github.com/MisahSaid/the-startup-responsive-interactieve-website/commit/06bd510f5f4c4cd3a981e9f189cd53e133012ed0)
