### ISSUE TITLE
Spelfoutje ;)

### ISSUE THREAD

**Issue by xxdaniquee** [MisahSaid/the-startup-responsive-interactieve-website#9]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/blob/7e5000b02217e6c58498d706fa60e69508635c7a/index.html#L67

Bij de closing tag heb je iMput neergezet, dit moet natuurlijk iNput zijn

**Comment by MisahSaid** [comment]
https://github.com/MisahSaid/the-startup-responsive-interactieve-website/commit/79a87fde2f9c793fac5adcb134a680197a032ebe
